iter13
size12/url-shortener pull request #13
Opened 2022-12-28 17:35 UTC by size12

2022-12-28 17:44 UTC, size12 commented
с наступающим :)

2023-01-04 20:12 UTC, Bazys requested changes
1. подключить линтер
2. подключить goimports
3. несколько вопросов по ходу пьесы

2023-01-04 20:12 UTC, Bazys commented on internal/config/config.go
>  func findFlag(name string, defVal string) string {
честно говоря упустил прошлый раз, а зачем тебе такой велосипед? чем не устраивает встроенные средства которые проходили в 7 инкременте?

2023-01-04 20:12 UTC, Bazys commented on internal/config/config.go
>  	if cfg.ServerAddress != aFlag && aFlag != DefaultServerAddress {
а если `env.Parse(&cfg)` с 41 строчки поставить после  флагов, то не нужны будут все эти ифы

2023-01-04 20:12 UTC, Bazys commented on internal/linkhelpers/linkhelpers.go
> +	var isErr409 error = nil
nil лишнее

2023-01-04 20:12 UTC, Bazys commented on internal/linkhelpers/linkhelpers.go
> +	_ "github.com/jackc/pgx/v5/stdlib"
зачем?

2023-01-04 20:12 UTC, Bazys commented on internal/linkhelpers/linkhelpers.go
> +		i += 1
```suggestion
		i++
```
 с питона перешел? ))))))

2023-01-04 20:12 UTC, Bazys commented on internal/linkhelpers/linkhelpers.go
> +var Error409 = errors.New("link is already in storage")
```suggestion
var Err409 = errors.New("link is already in storage")
```
префикс для таких ошибок Err

2023-01-04 20:12 UTC, Bazys commented on internal/linkhelpers/linkhelpers.go
> +	_, err = db.ExecContext(ctx, "CREATE TABLE IF NOT EXISTS links (id varchar(255), url varchar(255), cookie varchar(255))")
почитай в сторону миграторов для golang
1. https://github.com/golang-migrate/migrate
2. https://github.com/pressly/goose
они нужны для тех случаев, когда у тебя например сменился тип поля, а твоя конструкция этого сделать не сможет.

2023-01-07 08:15 UTC, size12 commented on internal/config/config.go
>  	if cfg.ServerAddress != aFlag && aFlag != DefaultServerAddress {
есть такое, поменял

2023-01-07 08:15 UTC, size12 commented on internal/config/config.go
>  func findFlag(name string, defVal string) string {
В тестах валилось, что переназначался флаг. Сейчас понял свою ошибку и исправил.

2023-01-07 08:16 UTC, size12 commented on internal/linkhelpers/linkhelpers.go
> +	var isErr409 error = nil
+

2023-01-07 08:17 UTC, size12 commented on internal/linkhelpers/linkhelpers.go
> +	_ "github.com/jackc/pgx/v5/stdlib"
может я конечно что-то не понимаю, но вроде бы в уроке было, что нужно так библиотеку для базы данных подключать, чтобы она сама себя зарегистрировала, и с ней можно было работать через database/sql

2023-01-07 08:17 UTC, size12 commented on internal/linkhelpers/linkhelpers.go
> +		i += 1
да))))

2023-01-07 08:17 UTC, size12 commented on internal/linkhelpers/linkhelpers.go
> +var Error409 = errors.New("link is already in storage")
поменял, приму к сведению

2023-01-07 09:24 UTC, size12 commented on internal/linkhelpers/linkhelpers.go
> +	_, err = db.ExecContext(ctx, "CREATE TABLE IF NOT EXISTS links (id varchar(255), url varchar(255), cookie varchar(255))")
хорошо, спасибо за совет

2023-01-07 09:26 UTC, size12 commented
из линтеров скачал staticcheck

2023-01-07 09:26 UTC, size12 commented on internal/linkhelpers/linkhelpers.go
> +	var isErr409 error = nil
+

2023-01-07 09:50 UTC, Bazys commented on internal/linkhelpers/linkhelpers.go
> +	_ "github.com/jackc/pgx/v5/stdlib"
такие импорты допустимы только в  main модуле

2023-01-07 09:51 UTC, Bazys approved these changes

2023-01-07 11:25 UTC, merged