iter14
size12/url-shortener pull request #14
Opened 2023-01-07 11:30 UTC by size12

2023-01-07 11:44 UTC, size12 commented
думал надо будет просто sync.Mutex добавить, ан нет) Буду ждать открытия уроков тогда

2023-01-12 13:48 UTC, size12 commented
До последнего думал, что тесты будут как на codeforces, если неоптимальное решение, то будет превышение по времени. Но я всё равно переделаю, уже придумал более-менее оптимальное решение.

2023-01-12 16:28 UTC, size12 commented
переделал, решил уж сегодня добить, что уж на потом оставлять)

2023-01-12 18:21 UTC, size12 commented
UPD: есть баг, пока не напишу, что решил его, можно не проверять

2023-01-13 06:44 UTC, Bazys requested changes

2023-01-13 06:44 UTC, Bazys commented on internal/linkhelpers/linkhelpers.go
> +// DBDeleteURLs идея такая: ждем по максимуму значения из канала links.willDelete, если они заканчиваются, то всё это добваляем в базу
есть другое решение - при удалении записи помечаем как удаленные и при селекте их не отбираем.
а потом раз в сутки ходит демон и подчищает удаленные записи

2023-01-13 06:44 UTC, Bazys commented on internal/app/app.go
> +	go links.DBDeleteURLs()
у тебя бесконтрольная горутина.
Надо в неё как минимум передать контекст с WithCancel  передать
почитай [здесь](https://medium.com/german-gorelkin/data-protected-by-confinement-ec6b7be401ea)

2023-01-19 10:33 UTC, size12 commented
Переделал на интерфейсную реализацию.

2023-01-19 10:45 UTC, size12 commented
Вопрос: как использовать контексты от запроса? у меня в мыслях только такой вариант: https://play.golang.com/p/_pXibgd98Ih

2023-01-21 18:37 UTC, Bazys approved these changes

2023-02-10 18:20 UTC, merged