iter8
size12/url-shortener pull request #8
Opened 2022-12-11 18:43 UTC by size12

2022-12-13 18:31 UTC, size12 commented
конкретно тупил как распаковать gzip тело запроса.

2022-12-14 14:07 UTC, Bazys requested changes

2022-12-14 14:07 UTC, Bazys commented on cmd/shortener/main.go
>  func main() {
может весь код по инициализации приложения вынести в отдельный сервис, типа App ?
а в main оставить только app.Run()

2022-12-14 14:07 UTC, Bazys commented on internal/config/config.go
> +func init() {
давай не пользоваться функциями init()
проблема с ними в том, что никто не гарантирует порядок их исполнения и если в другом модуле у тебя будет переопределение какой либо переменной вроде `ServerAddress` то какое значение в ней будет в итоге, никто не гарантирует.
Я понимаю ч то в учебных примерах к карлосу так написано, но погляди как это используется в серьезных приложениях, тот же github cli

2022-12-14 14:07 UTC, Bazys commented on internal/handlers/handlers.go
> +func URLGetHandler(cfg config.Config, links linkhelpers.Storage) http.HandlerFunc {
а если бы ты сделал структуру, в которой одно их полей это `config.Config`, то написав методы к этой структуре, не будет необходимости передавать это в качестве параметра.

2022-12-16 04:52 UTC, size12 commented
я надеюсь лучше стало :)

2022-12-18 09:36 UTC, Bazys approved these changes

2022-12-18 10:09 UTC, merged